# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ulj6gKa4HSFDIGsPjN-1WuGB0vJ5ssjB
"""

#install library
!pip install plotnine
!pip install imageio

#mengimport library
import numpy as np
import imageio
from  google.colab  import  files
import matplotlib.pyplot as plt

#membaca image
img = imageio.imread("gambar4.jpg")

#mendapatkan resolusi dan type image
img_height = img.shape[0]
img_width = img.shape[1]
img_channel = img.shape[2]
img_type = img.dtype

#membuat variabel image horizontal dan vertikal
img_flip_horizontal = np.zeros(img.shape, img_type)
img_flip_vertical = np.zeros(img.shape, img_type)

#membalik image secara horizontal
for y in range(0, img_height):
    for x in range(0, img_width):
        for c in range(0, img_channel):
            img_flip_horizontal[y][x][c] = img[y][img_width-1-x][c]

#membalik image secara vertikal
for y in range(0, img_height):
    for x in range(0, img_width):
        for c in range(0, img_channel):
            img_flip_vertical[y][x][c] = img[img_height-1-y][x][c]

#menampilkan image
plt.imshow(img_flip_horizontal)
plt.title("Flip Horizontal")
plt.show()
plt.imshow(img_flip_vertical)
plt.title("Flip Vertical")
plt.show()